### ISSUE TITLE
Zrevidovat podmínky ochrany osobních údajů

### ISSUE THREAD

**Issue by just-paja** [fantasion/fantasion#130]

**Comment by just-paja** [comment]
TODO: Prolinkovat staticky clanek cookies na web

**Comment by vitvrs** [comment]
> TODO: Prolinkovat staticky clanek cookies na web

Prolinkováno

**Comment by just-paja** [comment]
@vitvrs, @sarinkavr, v podmínkách o ochraně osobních údajů chybí výpis konkrétních údajů, se kterými Fantasion pracuje. Jsou tam příklady, ale to nestačí. Je potřeba mít u každého údaje uvedeno, za jakým účelem ho zpracováváme.

**Comment by sarinkavr** [comment]
Ok, doplním.

**Comment by sarinkavr** [comment]
## II. Zdroje a kategorie zpracovávaných osobních údajů
1.	Správce zpracovává osobní údaje, které jste mu poskytl/a nebo osobní údaje, které správce získal na základě plnění Vaší objednávky.
2.	Správce zpracovává Vaše identifikační a kontaktní údaje a údaje nezbytné pro plnění smlouvy. 
3.	Správce zpracovává následující osobní údaje:
			a) osobní údaje rodičů: jméno a příjmení, telefonní číslo, e-mailová adresa, adresa, číslo bankovního spojení,
			b) osobní údaje dětí přihlašovaných na tábor: jméno a příjmení, datum narození, informace o alergiích, dietách a zájmech dítěte, údaje o zdravotním stavu patřící do zvláštní kategorie osobních údajů v rozsahu „Posudku o zdravotní způsobilosti dítěte k účasti na zotavovací akci“ a „Potvrzení o bezinfekčnosti“ dle platných zákonů,
			c) zvláštní kategorie osobních údajů budou zpracovány za účelem dle čl. 9 odst. 2. písm. i) nařízení

**Comment by sarinkavr** [comment]
Já myslím, že done.

**Comment by just-paja** [comment]
Tak si to hoď na produkci a zavři ;-)

**Comment by vitvrs** [comment]
Done by @sarinkavr
