### ISSUE TITLE
Bestiář

### ISSUE THREAD

**Issue by vitvrs** [fantasion/fantasion#133]
Vytvoření bestiáře pro hru s promokódy.
Jedna stránka s textovým statickým polem pro vysvětlení soutěže a pak rozklikávací náhledy obrázků - stejné jako databáze našich instruktorů (Náš tým).
Ze stránky proklik na naše stránky (ale ne naopak). 
Na stránku by se šlo dostat pouze QR kódem.

**Comment by just-paja** [comment]
Přidáme do admina ještě políčko na fotku

**Comment by vitvrs** [comment]
Done.

**Comment by just-paja** [comment]
Není to zavřený dokud to není v masteru
