### ISSUE TITLE
Mrkající Zaklínač

### ISSUE THREAD

**Issue by vitvrs** [fantasion/fantasion#134]
Vyříznout oči které se budou po najetí myší zabarvovat.

**Comment by just-paja** [comment]
@vitvrs, koukal jsem na vyříznuté oči na disku, ale nesedí mi tam rozměry. Na disku jsou dvě varianty s rozměry 1181x591px, ale na webu používáme rozměry [520x585px](https://github.com/fantasion/fantasion/blob/master/packages/fantasion-web/public/witcher-xs.webp) a [640x720px](https://github.com/fantasion/fantasion/blob/master/packages/fantasion-web/public/witcher-xl.webp)
