### ISSUE TITLE
Přehledně zobrazit co vše je zahrnuto v ceně

### ISSUE THREAD

**Issue by vitvrs** [fantasion/fantasion#148]
Doprava, strava, ubytování atd. - kvůli obchodním podmínkám

**Comment by sarinkavr** [comment]
https://docs.google.com/document/d/11whCftlViM7s3R7_BAQjgZ5g0iFBFY4AChmZWQ3do7k/edit?usp=sharing

**Comment by just-paja** [comment]
20cde41c05060058ac86b36494502b0f314201a9
