### ISSUE TITLE
UX input na zadání telefonního čísla

### ISSUE THREAD

**Issue by just-paja** [fantasion/fantasion#158]

**Comment by vitvrs** [comment]
Pokud se ze zemí zvolí Česká republika, ukazuje to chorvatskou vlajku (a obávám se že to propisuje i chorvatskou předvolbu), vypadá to že země jsou o 4 posunuté, ale jen v horní části, Slovensko už to zase ukazuje normálně.

**Comment by just-paja** [comment]
Nahradil jsem to jiným inputem, otestoval a už to funguje.
