### ISSUE TITLE
Informace o dopravě

### ISSUE THREAD

**Issue by vitvrs** [fantasion/fantasion#182]
Článek, zobrazující se v "Mém přehledu" ve kterém budou shrnuty informace o odjezdu na tábor.

**Comment by just-paja** [comment]
@vitvrs, pojal jsem to trochu jinak. Snad je to v poho :-)

Doprava se dá sledovat a zveřejňovat atomicky. Přidal jsem modely TroopTransport, Transport, TransportVehicle, TransportVehicleMedia. Dá se pomocí toho udělat jednoduše info stránka dopravy, která jde poslat odkazem. Přišlo mi to jednodušší dát to jako veřejnou informaci, než se s tím trápit přes přihlašování.

Je tam příprava na GPS tracking autobusu (stačí nasdílet svojí pozici na telefonu a vložit odkaz). Odkaz se zobrazí jenom pokud je autobus zrovna ve stavu "na cestě". 

Dodatečné rich text info se dá na stránku naflákat pomocí `Transport.description` a `TransportVehicle.description`.
