### ISSUE TITLE
 Nefunkční omezení propagačních kódů

### ISSUE THREAD

**Issue by vitvrs** [fantasion/fantasion#210]
U propagačních kódů nefunguje odebrání možnosti "povolit" ani časové omezení a slevový kód tak není možné nijak vypnout nebo omezit. K zamezení požívání kódů z minulého roku bylo nutné odstranit všechny kódy, k čemuž bylo nutné odebrat jejich propojení ke konkrétním objednávkám. Při větším počtu přihlášek používajících slevový kód by to již bylo složité.

**Comment by just-paja** [comment]
Opraveno v 0441abbc13509653c0bb5ddac0aa46b079d40725
