### ISSUE TITLE
Secret přihlašování

### ISSUE THREAD

**Issue by vitvrs** [fantasion/fantasion#215]
Aby bylo možné udělat neveřejné přihlašování na ŠVP (případně na jiné akce, kterými nechceme spamovat hlavní stránku) přidalo by se k Táboru boolean pole "Tajné přihlašování". Při zaškrtnutí tohoto pole by se dělo následující:
- stránka tábora (např. "fantasion.cz/cs/tabory/zaklinac-2022-1/") by fungovala normálně včetně přihlašování
- na hlavní stránce, ani na stránce Dobrodružství by se tábor nezobrazil (= jediná možnost jak se na stránku s táborem dostat by byla přes přímý odkaz)

**Comment by just-paja** [comment]
@vitvrs, změnil jsem políčko "public" na "visibility". Varianta "private" by měla způsobit, že objekt nebude viditelný v seznamech, ale bude přístupný přes jeho přímý odkaz.

**Comment by vitvrs** [comment]
@just-paja Skvělý, ozkoušeno a krásně to funguje přesně tak jak to potřebujeme  :)
