### ISSUE TITLE
Oprava deníku

### ISSUE THREAD

**Issue by vitvrs** [fantasion/fantasion#223]
Deník se uživatelům nezobrazuje u žádné akce při jakémkoliv nastavení public/privat.

**Comment by just-paja** [comment]
[https://github.com/fantasion/fantasion/commit/917aa11bcbc52550765e68f501beb93d5ac639bd](https://github.com/fantasion/fantasion/commit/917aa11bcbc52550765e68f501beb93d5ac639bd?fbclid=IwAR3rLnUKF7dozQrP-N9mJgk-IL5J0VKN_Ywz6W6uU-K7FXalHrI_WtKYN3A)
