### ISSUE TITLE
Veřejné kanály

### ISSUE THREAD

**Issue by just-paja** [fantasion/fantasion#33]
Návštěvník webu potřebuje znát všechny veřejné kanály Fantasionu.

* e-mail
* telefon
* facebook
* twitter
* instagram
* youtube
* tiktok
* tinder

**Comment by just-paja** [comment]
@vitvrs, nahraješ mi sem odkazy na vaše veřejné kanály? Zatím mám jenom e-mail: info@fantasion.cz

**Comment by vitvrs** [comment]
jasně, veřejné kanály jsou následující:
instagram: fantasion_cz
tiktok: fantasion_cz
facebook: Fantasion

zbylé zatím nemáme, nejdůležitější je telefon na kterém se pracuje

**Comment by just-paja** [comment]
@vitvrs, přidal jsem to do odkazů. Na další prosím založ nový úkol, až budou dostupné.
