### ISSUE TITLE
E-mailový robot

### ISSUE THREAD

**Issue by just-paja** [fantasion/fantasion#83]
Pod jakým jménem bude vystupovat e-mailový robot Fantasionu? Poločas má Karla.

**Comment by vitvrs** [comment]
Pokud nejni nutné aby byli roboti nějak specificky genderově zaměření tak jsme se shodli, že by to mohla být "Cítí" - ženského pohlaví 😁

**Comment by just-paja** [comment]
@vitvrs,

**Comment by vitvrs** [comment]
Ok, koukám že mi to jméno upravila korektura na mobilu 😆 měla to být "Ciri", přepíšu si ji tam 😁

**Comment by just-paja** [comment]
@vitvrs, budu očekávat Pull request ;-)
