### ISSUE TITLE
INTRO - Hlavní stránka, která zaujme

### ISSUE THREAD

**Issue by vitvrs** [fantasion/fantasion#88]
Hlavní stránka s nejkoncentrovanějšími informacemi:
- Co bude zajímavého na našem táboře
- Proč to bude jiné než jiné tábory - zážitková pedagogika
- Kolik to stojí + odkaz na přihlášku

**Comment by just-paja** [comment]
@vitvrs , jsou někde materiály, které by se daly přepracovat do podoby takové homepage? Nevím co bude zajímavého na vašem táboře :-D

**Comment by vitvrs** [comment]
[Dokument s informacemi na stránky](https://docs.google.com/document/d/1afzS-jgO7NUma4mf2DvAtbF_6wS4MYVNvLTt6J4c6xc/edit?usp=sharing)

**Comment by just-paja** [comment]
Stránka vytvořena. Pokud na ní něco bude chybět, prosím vytvořit konkrétní úkol.
